contentColumnType: text
fieldGroup: 22a4cb8c-09d7-4561-adf3-5b4ad79ba412
handle: emailAddress
instructions: 'Your work email address'
name: 'Email Address'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g. - m.scott@dundermifflin.co'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
